### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by laszloforgacs** [ITU-DevOps-N/go-minitwit#83]
- [x]  Functional timeline with twits received from simulator

- [x]  Signup

- [x] Login/logout

- [x] Another user’s timeline

- [x] Follow/Unfollow functionalities

- [x] Twit appears on timeline after publishing

There is not much to say as the application seems to be working fine, sometimes it takes some time to perform actions, but great job!

**Comment by emilravn** [comment]
Thanks for the feedback!
